import type { Metadata } from "next";
import { Fira_Code } from 'next/font/google';
import "./globals.css";

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code', // optional: useful for Tailwind
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Romel Custodio | Front End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" app-version="release-v1.6">
      <body
        className={`${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
